kind: pipeline
type: docker
name: shop-mobile

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
    when:
      branch:
        - master
      event:
        - push

  - name: build
    image: node:8.15
    volumes:
      - name: app-config
        path: /root/app-config
    commands:
      - npm config set registry https://registry.npm.taobao.org/
      - npm install
      - cp -f /root/app-config/global.ts  src/global.ts
      - ionic build --prod
      - ls
      - mkdir context
      - mv www context/dist
      - mv Dockerfile context/Dockerfile
    when:
      branch:
        - master
      event:
        - push

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    when:
      branch:
        - master
      event:
        - push

  - name: deploy
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - cd context
      - docker stop shop-mobile || true
      - docker rm shop-mobile || true
      - docker rmi shop-mobile:1.0 || true
      - docker build -t shop-mobile:1.0 .
      - docker run -d -p 80:80 --name shop-mobile --restart always shop-mobile:1.0
    when:
      branch:
        - master
      event:
        - push

volumes:
  - name: cache
    host:
      path: /data/node_modules_cache
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: app-config
    host:
      path: /root/app-config
